apiVersion: v1
kind: ConfigMap
metadata:
  name: my-python-app-config
data:
  APP_COLOR: "blue"
  MY_NAME: "Masih"
  BACKGROUND_IMAGE: "https://masihbucket.s3.amazonaws.com/the_elder_scrolls_v_skyrim-wallpaper-1920x1200.jpg"